# -*- coding: utf-8 -*-
"""Vision Based Pick Remmendation System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17g-4FuxhWlh0djenEisCa79C9ioTWKDY
"""

# ============================================================
# WAREHOUSE VISION-BASED PRODUCT RECOMMENDATION
# COMPLETE FLOW — SINGLE COLAB CELL
# ============================================================

# -----------------------------
# 1. INSTALL DEPENDENCIES
# -----------------------------
!pip install -q -U ultralytics huggingface_hub sentence-transformers transformers google-genai opencv-python

# -----------------------------
# 2. IMPORTS
# -----------------------------
import os
import re
import json
import cv2
import numpy as np
import pandas as pd
import torch

from PIL import Image
from IPython.display import display
from getpass import getpass

from google.colab import drive
from huggingface_hub import hf_hub_download

from ultralytics import YOLO
from sentence_transformers import SentenceTransformer
from transformers import AutoProcessor, AutoModelForZeroShotImageClassification
from google import genai


# ============================================================
# 3. MOUNT GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")

PROJECT_DIR = "/content/drive/MyDrive/Warehouse Vision-Based Pick Recommendation System"

print("Project folder:")
print(PROJECT_DIR)


# ============================================================
# 4. LOAD PROJECT CSV FILES
# ============================================================

cv_path = os.path.join(PROJECT_DIR, "cv_images.csv")
inventory_path = os.path.join(PROJECT_DIR, "inventory.csv")
orders_path = os.path.join(PROJECT_DIR, "orders.csv")
warehouse_path = os.path.join(PROJECT_DIR, "warehouse_locations.csv")

cv_images_df = pd.read_csv(cv_path)
inventory_df = pd.read_csv(inventory_path)
orders_df = pd.read_csv(orders_path)
warehouse_df = pd.read_csv(warehouse_path)

print("\nCSV FILES LOADED")
print("----------------")
print("cv_images:", cv_images_df.shape)
print("inventory:", inventory_df.shape)
print("orders:", orders_df.shape)
print("warehouse:", warehouse_df.shape)


# ============================================================
# 5. BUILD PRODUCT CATALOG
# ============================================================

required_columns = ["Product_ID", "Product_Name"]

for col in required_columns:
    if col not in orders_df.columns:
        raise ValueError(
            f"Required column '{col}' is missing from orders.csv"
        )

catalog_columns = [
    "Product_ID",
    "Product_Name",
    "Category"
]

available_columns = [
    c for c in catalog_columns
    if c in orders_df.columns
]

product_catalog = (
    orders_df[available_columns]
    .drop_duplicates("Product_ID")
    .reset_index(drop=True)
)

if "Category" not in product_catalog.columns:
    product_catalog["Category"] = "Unknown"

product_catalog["Product_ID"] = (
    product_catalog["Product_ID"]
    .astype(str)
    .str.strip()
)

product_catalog["Product_Name"] = (
    product_catalog["Product_Name"]
    .astype(str)
    .str.strip()
)

product_catalog["Category"] = (
    product_catalog["Category"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
)

print("\nPRODUCT CATALOG")
print("----------------")
print("Unique products:", len(product_catalog))


# ============================================================
# 6. TEXT RAG DATABASE
# ============================================================

product_documents = [
    f"""
Product ID: {row['Product_ID']}
Product Name: {row['Product_Name']}
Category: {row['Category']}
""".strip()

    for _, row in product_catalog.iterrows()
]

print("\nRAG DOCUMENTS CREATED:", len(product_documents))


# ============================================================
# 7. LOAD TEXT EMBEDDING MODEL
# ============================================================

print("\nLoading RAG embedding model...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

product_embeddings = embedding_model.encode(
    product_documents,
    normalize_embeddings=True,
    show_progress_bar=True
)

product_embeddings = np.asarray(product_embeddings)

print("RAG embeddings shape:", product_embeddings.shape)


# ============================================================
# 8. RAG RETRIEVAL FUNCTION
# ============================================================

def retrieve_products(query, top_k=10):

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    scores = product_embeddings @ query_embedding

    top_indices = np.argsort(scores)[::-1][:top_k]

    results = []

    for idx in top_indices:

        row = product_catalog.iloc[idx]

        results.append({
            "Product_ID": str(row["Product_ID"]),
            "Product_Name": str(row["Product_Name"]),
            "Category": str(row["Category"]),
            "rag_score": float(scores[idx])
        })

    return results


# ============================================================
# 9. LOAD PRETRAINED YOLO MODEL
# ============================================================

print("\nDownloading YOLO model...")

HF_REPO_ID = "prince4332/yolov26-product-detection-v2"
MODEL_FILENAME = "best.pt"

model_path = hf_hub_download(
    repo_id=HF_REPO_ID,
    filename=MODEL_FILENAME
)

yolo_model = YOLO(model_path)

print("YOLO model loaded")
print("YOLO classes:", yolo_model.names)


# ============================================================
# 10. OPENCV PREPROCESSING
# ============================================================

def preprocess_image_opencv(pil_image):

    img = np.array(pil_image)

    # RGB -> BGR
    img = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2BGR
    )

    # Resize large images
    max_size = 1280

    height, width = img.shape[:2]

    scale = min(
        max_size / width,
        max_size / height,
        1.0
    )

    if scale < 1.0:

        new_width = int(width * scale)
        new_height = int(height * scale)

        img = cv2.resize(
            img,
            (new_width, new_height),
            interpolation=cv2.INTER_AREA
        )

    # Light noise reduction
    img = cv2.GaussianBlur(
        img,
        (3, 3),
        0
    )

    return img


# ============================================================
# 11. YOLO OBJECT DETECTION
# ============================================================

def detect_with_yolo(pil_image):

    processed = preprocess_image_opencv(
        pil_image
    )

    results = yolo_model.predict(
        source=processed,
        conf=0.25,
        iou=0.45,
        verbose=False
    )

    result = results[0]

    detections = []

    if result.boxes is None:
        return detections

    for box in result.boxes:

        class_id = int(
            box.cls[0].item()
        )

        confidence = float(
            box.conf[0].item()
        )

        xyxy = (
            box.xyxy[0]
            .cpu()
            .numpy()
        )

        detections.append({

            "class_id": class_id,

            "class_name": yolo_model.names[class_id],

            "confidence": confidence,

            "bbox": [
                float(x)
                for x in xyxy
            ]
        })

    return detections


# ============================================================
# 12. YOLO PRODUCT CROP
# ============================================================

def get_yolo_product_crop(
    pil_image,
    confidence_threshold=0.25
):

    results = yolo_model.predict(
        source=np.array(pil_image),
        conf=confidence_threshold,
        iou=0.45,
        verbose=False
    )

    result = results[0]

    if (
        result.boxes is None
        or len(result.boxes) == 0
    ):
        return None, []

    detections = []

    best_box = None
    best_confidence = 0

    for box in result.boxes:

        class_id = int(
            box.cls[0].item()
        )

        confidence = float(
            box.conf[0].item()
        )

        xyxy = (
            box.xyxy[0]
            .cpu()
            .numpy()
        )

        detection = {

            "class_id": class_id,

            "class_name":
                yolo_model.names[class_id],

            "confidence":
                confidence,

            "bbox":
                [float(x) for x in xyxy]
        }

        detections.append(
            detection
        )

        if confidence > best_confidence:

            best_confidence = confidence
            best_box = xyxy

    if best_box is None:
        return None, detections

    x1, y1, x2, y2 = map(
        int,
        best_box
    )

    width, height = pil_image.size

    x1 = max(
        0,
        min(x1, width)
    )

    x2 = max(
        0,
        min(x2, width)
    )

    y1 = max(
        0,
        min(y1, height)
    )

    y2 = max(
        0,
        min(y2, height)
    )

    if (
        x2 <= x1
        or y2 <= y1
    ):
        return None, detections

    cropped_image = pil_image.crop(
        (x1, y1, x2, y2)
    )

    return (
        cropped_image,
        detections
    )


# ============================================================
# 13. LOAD PRETRAINED VISION MODEL
# ============================================================

print("\nLoading CLIP vision model...")

VISION_MODEL = "openai/clip-vit-base-patch32"

vision_processor = AutoProcessor.from_pretrained(
    VISION_MODEL
)

vision_model = (
    AutoModelForZeroShotImageClassification
    .from_pretrained(VISION_MODEL)
)

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

vision_model = vision_model.to(device)
vision_model.eval()

print("Vision device:", device)


# ============================================================
# 14. IMAGE PRODUCT IDENTIFICATION
# ============================================================

def identify_product_from_image(
    image,
    top_k=5
):

    product_names = (
        product_catalog["Product_Name"]
        .tolist()
    )

    labels = [
        f"a photo of {name}"
        for name in product_names
    ]

    inputs = vision_processor(
        text=labels,
        images=image,
        return_tensors="pt",
        padding=True
    )

    inputs = {
        k: v.to(device)
        for k, v in inputs.items()
    }

    with torch.no_grad():

        outputs = vision_model(
            **inputs
        )

    logits = outputs.logits_per_image

    probabilities = (
        logits.softmax(dim=1)
        .cpu()
        .numpy()[0]
    )

    top_indices = np.argsort(
        probabilities
    )[::-1][:top_k]

    results = []

    for idx in top_indices:

        row = product_catalog.iloc[idx]

        results.append({

            "Product_ID":
                str(row["Product_ID"]),

            "Product_Name":
                str(row["Product_Name"]),

            "Category":
                str(row["Category"]),

            "score":
                float(probabilities[idx])
        })

    return results


# ============================================================
# 15. GEMINI API
# ============================================================

print("\nEnter Gemini API key:")

API_KEY = getpass(
    "Gemini API Key: "
)

client = genai.Client(
    api_key=API_KEY
)

print("Gemini client ready.")


# ============================================================
# 16. GEMINI PRODUCT RECOMMENDATION
# ============================================================

def generate_recommendations(
    detected_product,
    rag_products,
    number_of_recommendations=5
):

    candidate_text = "\n".join([

        f"""
Product_ID: {p['Product_ID']}
Product_Name: {p['Product_Name']}
Category: {p['Category']}
RAG_Score: {p['rag_score']:.4f}
""".strip()

        for p in rag_products
    ])

    prompt = f"""
You are a product recommendation engine.

Detected product:

Product_ID:
{detected_product['Product_ID']}

Product_Name:
{detected_product['Product_Name']}

Category:
{detected_product['Category']}

RAG candidate products:

{candidate_text}

Task:

Recommend exactly
{number_of_recommendations}
products.

Rules:

1. Do NOT recommend the detected product.
2. Use ONLY the RAG candidate products.
3. Do NOT invent products.
4. Do NOT invent Product_IDs.
5. Preserve Product_ID exactly.
6. Preserve Product_Name exactly.
7. Prefer complementary or useful products.
8. Return JSON only.

Required format:

{{
  "recommendations": [
    {{
      "Product_ID": "P00000",
      "Product_Name": "Exact Product Name"
    }}
  ]
}}
"""

    interaction = client.interactions.create(
        model="gemini-3.6-flash",
        input=prompt
    )

    text = interaction.output_text.strip()

    # Remove markdown code fences
    text = re.sub(
        r"^```json\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\s*```$",
        "",
        text
    )

    data = json.loads(text)

    valid_products = {
        p["Product_ID"]:
            p["Product_Name"]

        for p in rag_products
    }

    detected_id = (
        detected_product["Product_ID"]
    )

    final_recommendations = []

    for item in data.get(
        "recommendations",
        []
    ):

        product_id = str(
            item.get(
                "Product_ID",
                ""
            )
        ).strip()

        if product_id not in valid_products:
            continue

        if product_id == detected_id:
            continue

        final_recommendations.append({

            "Product_ID":
                product_id,

            "Product_Name":
                valid_products[
                    product_id
                ]
        })

    # Remove duplicates
    unique = {}

    for item in final_recommendations:

        unique[
            item["Product_ID"]
        ] = item

    return {
        "recommendations":
            list(unique.values())[
                :number_of_recommendations
            ]
    }


# ============================================================
# 17. DRAW YOLO DETECTIONS
# ============================================================

def draw_yolo_detections(
    pil_image,
    detections
):

    img = np.array(
        pil_image
    )

    img = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2BGR
    )

    for detection in detections:

        x1, y1, x2, y2 = map(
            int,
            detection["bbox"]
        )

        class_name = (
            detection["class_name"]
        )

        confidence = (
            detection["confidence"]
        )

        label = (
            f"{class_name} "
            f"{confidence:.2f}"
        )

        cv2.rectangle(
            img,
            (x1, y1),
            (x2, y2),
            (0, 255, 0),
            3
        )

        cv2.putText(
            img,
            label,
            (
                x1,
                max(
                    y1 - 10,
                    25
                )
            ),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    img = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2RGB
    )

    return img


# ============================================================
# 18. COMPLETE AI PIPELINE
# ============================================================

def final_warehouse_pipeline(
    pil_image,
    top_k_vision=5,
    top_k_rag=10
):

    # -----------------------------------
    # STEP A — YOLO DETECTION
    # -----------------------------------

    product_crop, yolo_detections = (
        get_yolo_product_crop(
            pil_image
        )
    )

    if product_crop is None:

        return {

            "status": "failed",

            "stage": "YOLO",

            "message":
                "YOLO could not detect a product.",

            "yolo_detections":
                []
        }

    # -----------------------------------
    # STEP B — PRODUCT IDENTIFICATION
    # -----------------------------------

    vision_results = (
        identify_product_from_image(
            product_crop,
            top_k=top_k_vision
        )
    )

    if not vision_results:

        return {

            "status": "failed",

            "stage": "VISION",

            "message":
                "Product identification failed.",

            "yolo_detections":
                yolo_detections
        }

    detected_product = (
        vision_results[0]
    )

    # -----------------------------------
    # STEP C — TEXT RAG
    # -----------------------------------

    rag_query = (
        f"{detected_product['Product_Name']} "
        f"{detected_product['Category']}"
    )

    rag_products = retrieve_products(
        rag_query,
        top_k=top_k_rag
    )

    # Remove detected product
    rag_products = [
        p
        for p in rag_products
        if p["Product_ID"]
        != detected_product["Product_ID"]
    ]

    # -----------------------------------
    # STEP D — GEMINI RECOMMENDATION
    # -----------------------------------

    recommendation_result = (
        generate_recommendations(
            detected_product=
                detected_product,

            rag_products=
                rag_products,

            number_of_recommendations=5
        )
    )

    recommendations = (
        recommendation_result
        .get(
            "recommendations",
            []
        )
    )

    # -----------------------------------
    # FINAL VALIDATION
    # -----------------------------------

    rag_ids = {
        p["Product_ID"]
        for p in rag_products
    }

    valid_recommendations = [

        p
        for p in recommendations

        if (
            p["Product_ID"]
            in rag_ids
        )

        and (
            p["Product_ID"]
            != detected_product[
                "Product_ID"
            ]
        )
    ]

    return {

        "status":
            "success",

        "yolo": {

            "detections":
                yolo_detections,

            "best_detection":
                yolo_detections[0]
                if yolo_detections
                else None
        },

        "product_detection": {

            "Product_ID":
                detected_product[
                    "Product_ID"
                ],

            "Product_Name":
                detected_product[
                    "Product_Name"
                ],

            "Category":
                detected_product[
                    "Category"
                ],

            "Vision_Score":
                detected_product.get(
                    "score",
                    0
                )
        },

        "vision_top_predictions":
            vision_results,

        "rag_candidates":
            rag_products,

        "recommendations":
            valid_recommendations
    }


# ============================================================
# 19. UPLOAD PRODUCT IMAGE
# ============================================================

from google.colab import files

print("\n")
print("=" * 75)
print("UPLOAD PRODUCT IMAGE")
print("=" * 75)

uploaded = files.upload()

if not uploaded:

    raise ValueError(
        "No image uploaded."
    )

image_path = (
    list(uploaded.keys())[0]
)

image = Image.open(
    image_path
).convert("RGB")

print(
    "\nImage:",
    image_path
)

print(
    "Image size:",
    image.size
)


# ============================================================
# 20. RUN COMPLETE PIPELINE
# ============================================================

print("\n")
print("=" * 75)
print("RUNNING COMPLETE AI PIPELINE")
print("=" * 75)

final_result = (
    final_warehouse_pipeline(
        image,
        top_k_vision=5,
        top_k_rag=10
    )
)


# ============================================================
# 21. DISPLAY ORIGINAL IMAGE
# ============================================================

print("\n📷 ORIGINAL IMAGE")
display(image)


# ============================================================
# 22. DISPLAY YOLO DETECTION
# ============================================================

print("\n🎯 YOLO DETECTION")

if final_result["status"] == "success":

    detections = (
        final_result["yolo"]
        ["detections"]
    )

    annotated_image = (
        draw_yolo_detections(
            image,
            detections
        )
    )

    display(
        Image.fromarray(
            annotated_image
        )
    )

    print(
        "\nYOLO detections:"
    )

    for d in detections:

        print(
            f"  {d['class_name']} | "
            f"Confidence: "
            f"{d['confidence']:.3f}"
        )

else:

    print(
        final_result["message"]
    )


# ============================================================
# 23. DISPLAY CROPPED PRODUCT
# ============================================================

print("\n✂️ YOLO PRODUCT CROP")

product_crop, _ = (
    get_yolo_product_crop(
        image
    )
)

if product_crop is not None:

    display(product_crop)

else:

    print(
        "No product crop available."
    )


# ============================================================
# 24. PRODUCT IDENTIFICATION
# ============================================================

print("\n")
print("=" * 75)
print("🤖 PRODUCT IDENTIFICATION")
print("=" * 75)

if final_result["status"] == "success":

    detected = (
        final_result[
            "product_detection"
        ]
    )

    print(
        "Product ID   :",
        detected["Product_ID"]
    )

    print(
        "Product Name :",
        detected["Product_Name"]
    )

    print(
        "Category     :",
        detected["Category"]
    )

    print(
        "Vision Score :",
        round(
            detected["Vision_Score"],
            4
        )
    )


# ============================================================
# 25. TOP VISION PREDICTIONS
# ============================================================

print("\n")
print("=" * 75)
print("🔎 TOP VISION PREDICTIONS")
print("=" * 75)

if final_result["status"] == "success":

    for i, p in enumerate(
        final_result[
            "vision_top_predictions"
        ],
        1
    ):

        print(
            f"{i}. "
            f"{p['Product_Name']} "
            f"({p['Product_ID']}) "
            f"| Score: "
            f"{p['score']:.4f}"
        )


# ============================================================
# 26. RAG RESULTS
# ============================================================

print("\n")
print("=" * 75)
print("📚 RAG CANDIDATES")
print("=" * 75)

if final_result["status"] == "success":

    for i, p in enumerate(
        final_result[
            "rag_candidates"
        ],
        1
    ):

        print(
            f"{i}. "
            f"{p['Product_Name']} "
            f"({p['Product_ID']}) "
            f"| {p['Category']} "
            f"| RAG: "
            f"{p['rag_score']:.4f}"
        )


# ============================================================
# 27. FINAL GEMINI RECOMMENDATIONS
# ============================================================

print("\n")
print("=" * 75)
print("🛒 AI PRODUCT RECOMMENDATIONS")
print("=" * 75)

if final_result["status"] == "success":

    recommendations = (
        final_result[
            "recommendations"
        ]
    )

    if recommendations:

        for i, p in enumerate(
            recommendations,
            1
        ):

            print(
                f"{i}. "
                f"{p['Product_Name']} "
                f"({p['Product_ID']})"
            )

    else:

        print(
            "No valid recommendations."
        )


# ============================================================
# 28. FINAL SYSTEM VALIDATION
# ============================================================

print("\n")
print("=" * 75)
print("✅ SYSTEM VALIDATION")
print("=" * 75)

if final_result["status"] == "success":

    checks = {

        "OpenCV preprocessing":
            True,

        "YOLO detection":
            len(
                final_result[
                    "yolo"
                ]["detections"]
            ) > 0,

        "Product identification":
            bool(
                final_result[
                    "product_detection"
                ]["Product_ID"]
            ),

        "RAG retrieval":
            len(
                final_result[
                    "rag_candidates"
                ]
            ) > 0,

        "Gemini recommendation":
            len(
                final_result[
                    "recommendations"
                ]
            ) > 0
    }

    for name, passed in checks.items():

        print(
            f"{'✅' if passed else '❌'} "
            f"{name}: "
            f"{'PASS' if passed else 'FAIL'}"
        )

    print("\n")
    print("=" * 75)
    print("FINAL PIPELINE")
    print("=" * 75)

    print(
        "IMAGE"
        " → OpenCV"
        " → YOLO"
        " → PRODUCT IDENTIFICATION"
        " → TEXT RAG"
        " → GEMINI"
        " → RECOMMENDATIONS"
    )

else:

    print(
        "❌ Pipeline failed at:",
        final_result["stage"]
    )

    print(
        final_result["message"]
    )